included:
- Howdy/

# Lint対象から除外するパス
excluded:
- Pods/
- Podfile
- Podfile.lock
- HowdyTests/
- HowdyUITests/

# 無効にするルール
disabled_rules:
- unneeded_override
# コード記載のない改行を許可するため
- trailing_whitespace
# closureが返す値を明示しておきたい場合があるため
- unused_closure_parameter
- force_cast

# デフォルト無効のルールのうち、有効にするもの
opt_in_rules:
- closure_end_indentation
- closure_spacing
- collection_alignment
- conditional_returns_on_newline # ガード文などは簡潔に一行で記述したいため
- empty_count
- explicit_self
- explicit_init
- fatal_error_message
- first_where
- force_unwrapping
- implicitly_unwrapped_optional
- missing_docs
- nimble_operator
- number_separator
- operator_usage_whitespace
- overridden_super_call
- private_outlet
- prohibited_super_call
- redundant_nil_coalescing
- sorted_imports

# 1行の文字列制限
line_length:
- 200   # warning
- 300   # error

# 型の行数制限
type_body_length:
- 400   # warning
- 600   # error

# 1ファイルの行数制限
file_length:
- 500   # warning
- 1000  # error

# メソッドの行数制限
function_body_length:
- 100   # warning
- 200   # error

type_name:
min_length: 3
max_length:
warning: 40
error: 50
excluded:

# 変数名に関する制約
identifier_name:
min_length: # only min_length
error: 2 # only error
excluded: # excluded via string array
- id
- URL
reporter: "xcode"
